### ISSUE TITLE
Rclone command not work in ttyd

### ISSUE THREAD

**Issue by Th4Park** [wy580477/Heroku-AIO-APP-EX#2]

**Comment by wy580477** [comment]
Rclone is under /workdir.  File name is randomized.

**Comment by Th4Park** [comment]
I don't know anything let it go, please add rclone web in new features like sync, copy, move, daily auto sync etc..

I synced with heroku's shellboat and rclone sync, so it is getting more speed, and it is getting less, why.

**Comment by wy580477** [comment]
> I don't know anything let it go, please add rclone web in new features like sync, copy, move, daily auto sync etc..
> 
> I synced with heroku's shellboat and rclone sync, so it is getting more speed, and it is getting less, why.

For copy, you can drag folder/file via Rclone WebUI explorer. 

For move, use this frontend to connect to your app. It has more advanced file manage functions than stock WebUI.
https://elonh.github.io/RcloneNg

For auto sync, I think you should to use script to call API via Rclone RC interface.
```
curl -s -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"srcFs":"'"${PATH_1}"'","dstFs":"'"${PATH_2}"'/'"$2"'","_async":"true"}' 'localhost:61802/sync/sync''
```

For speed, I can't help.

**Comment by Th4Park** [comment]
used ps then it came
I don't know what to do now


~$ ps
pid user time command
    1 none 0:00 ps-run
    3 u31083 0:00 runvdir -P /etc/service
   15 u31083 0:00 Runv 3
   16 u31083 0:00 Runv 2
   17 u31083 0:00 runv 1
   18 u31083 0:00 runv tyd
   19 u31083 0:00 Runv 5
   20 u31083 0:00 Runavi Caddy
   21 u31083 0:00 runv filebrowser
   22 u31083 0:00 runv backup_files
   23 u31083 0:00 runv olivetin
   24 u31083 0:00 Runv 4
   25 u31083 0:00 svlogd /mnt/data/log/aria2
   26 u31083 0:00 svlogd /mnt/data/log/ttyd
   27 u31083 0:00 svlogd /mnt/data/log/qbittorrent
   28 u31083 0:00 svlogd -tt /mnt/data/log/olivetin
   29 u31083 0:00 ttyd -i 127.0.0.1 -p 61803 -P 3 -t fontSize=17 -t titleFixed=Heroku_ttyd -t theme={"background": "black"} bash --rc
   30 u31083 0:00 /workdir/2bc0b68 --conf-path=/tmp/2bc0b68.conf --enable-rpc --rpc-secret=********* --rpc-listen-port=61800
   31 u31083 0:01 /workdir/182fb48 --webui-port=61804 --profile=/mnt/data/config
   32 u31083 0:00 svlogd -tt /mnt/data/log/caddy
   33 u31083 0:00 olivetin --configdir /mnt/data/config/olivetin
   34 u31083 0:09 caddy run --config /workdir/Caddyfile --adapter caddyfile
   35 u31083 0:00 svlogd /mnt/data/log/filebrowser
   36 u31083 0:00 filebrowser -d /mnt/data/config/filebrowser.db -b /mypath/files -p 61801
   37 u31083 0:00 svlogd -tt /mnt/data/log/backup_files
   40 u31083 0:00 svlogd /mnt/data/log/rclone
   41 u31083 0:00 /workdir/58854eb rcd --rc-serve --rc-web-gui-no-open-browser --rc-htpasswd=/workdir/htpasswd --rc-addr=localhost:61
   44 u31083 0:00 svlogd /mnt/data/log/rclone_webdav
   45 u31083 0:00 /workdir/62d1cea serve webdav W-1080:/ --htpasswd=/workdir/htpasswd_webdav --addr=localhost:61805 --buffer-size 4M
   46 u31083 0:00 svlogd /mnt/data/log/xray
   47 u31083 0:00 /workdir/33b4f1c -config=/tmp/3b4f1c.yaml
   66 u31083 0:01 [yt-dlp]
  215 u31083 0:00 bash --rcfile /mnt/data/config/bashrc
  264 u31083 0:00 {run} /bin/sh ./run
  265 u31083 000 sleep 600
  271 u31083 0:00 bash --rcfile /mnt/data/config/bashrc
  272 u31083 0:00 ps

**Comment by wy580477** [comment]
> used ps then it came I don't know what to do now

Rclone filename gets randomized every time when dyno restarts.

The better way is calling API via Rclone RC interface. See /content/qbittorclone.sh for example.

**Comment by wy580477** [comment]
I going to close this and edit your post. Rclone file is hard to find for a reason, if you run rclone as orginal file name, you dyno will get banned very quickly.

**Comment by Th4Park** [comment]
last question how to call api with the help of rclone rc because i have to use rclone command in ttyd
&
I don't know how to use it, please let me know, so that I can probably use Rclone Auto Sync in it.

**Comment by wy580477** [comment]
> last question how to call api with the help of rclone rc because i have to use rclone command in ttyd & I don't know how to use it, please let me know, so that I can probably use Rclone Auto Sync in it.
I already give you an example above.

```
curl -s -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"srcFs":"Remote_1:/path_1","dstFs":"Remote_2:/path_2","_async":"true"}' 'localhost:61802/sync/sync'
```

For more information, see offical docs: https://rclone.org/rc/

**Comment by Th4Park** [comment]
But you didn't tell me how to use this command, using in cmd or in ttyd 😅

**Comment by wy580477** [comment]
> But you didn't tell me how to use this command, using in cmd or in ttyd 😅

Run in ttyd.  Replace remote & path with your own.

**Comment by Th4Park** [comment]
it came written

~$ curl -s -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"srcFs":"re-1.3:/path_1"," dstFs":"Rre-1.2:/path_2",,"_async":"true"}' 'localhost:61802/sync/sync'
,
          "jobbid": 154
,
,

**Comment by wy580477** [comment]
> it came written
> 
> ~curl−s−u{GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"srcFs":"re-1.3:/path_1"," dstFs":"Rre-1.2:/path_2",,"_async":"true"}' 'localhost:61802/sync/sync' , "jobbid": 154 , ,

Go to WebUI to see if transfers occur.

**Comment by Th4Park** [comment]
oh great guruji it's done

**Comment by Th4Park** [comment]
Tell me one thing, don't you find this a bit complicated?

**Comment by wy580477** [comment]
> Tell me one thing, don't you find this a bit complicated?

Well, after losing several accounts in a row, this is my last resort. If heroku still can find out, I'm out of option.

**Comment by Th4Park** [comment]
Hey don't do this, I really liked your work, it is a bit complicated but this project of yours is cool🔥

**Comment by Th4Park** [comment]
You do only one thing, if you close this project, then work on the bot of telegram because there is no developer like you

**Comment by wy580477** [comment]
> Tell me one thing, don't you find this a bit complicated?

You can edit olivetin/config.yaml under config folder to add commands to OliveTin WebUI.

**Comment by Th4Park** [comment]
> > Tell me one thing, don't you find this a bit complicated?
> 
> Well, after losing several accounts in a row, this is my last resort. If heroku still can find out, I'm out of option.

> > last question how to call api with the help of rclone rc because i have to use rclone command in ttyd & I don't know how to use it, please let me know, so that I can probably use Rclone Auto Sync in it.
> 
> Following is an example for sync
> 
> ```
> curl -s -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"srcFs":"Remote_1:/path_1","dstFs":"Remote_2:/path_2","_async":"true"}' 'localhost:61802/sync/sync'
> ```
> 
> For more information, see offical docs: https://rclone.org/rc/

If I want to put a different command in it, then how to do it?

**Comment by wy580477** [comment]
> If I want to put a different command in it, then how to do it?

move:  'localhost:61802/sync/move'
copy:   'localhost:61802/sync/copy'

Unlike rclone move/copy, the above commands only support dirs not files.

For more commands:
https://rclone.org/rc/#supported-commands

**Comment by Th4Park** [comment]
not this command, such as finding the size of the remote
like -  Such as | rclone size Remote:

**Comment by wy580477** [comment]
> not this command, such as finding the size of the remote like - Such as | rclone size Remote:

Come on, read docs please. It‘s "operations/fsinfo"

Or you can view this info in WebUI. 
![image](https://user-images.githubusercontent.com/98247050/169693882-3bd03a5b-2380-4ffd-a99d-a48c02a8bbae.png)

**Comment by Th4Park** [comment]
~$ curl --data "re-1.2=1" --data "one=2" localhost:61802/rc/noopUnauthorized
~$ curl --data "re-1.2=1" --data "one=2" localhost:5572/rc/noop
curl: (7) Failed to connect to localhost port 5572 after 0 ms: Connection refused
~$ curl -H "Content-Type: application/json" -X POST -d '{"re-1.2":2,"one":1}' http://localhost:5572/rc/noop
curl: (7) Failed to connect to localhost port 5572 after 0 ms: Connection refused
~$ curl -H "Content-Type: application/json" -X POST -d '{"re-1.2":2,"one":1}' http://localhost:61802/rc/noop
Unauthorized

**Comment by Th4Park** [comment]
how to solw
and i was use copy command then show directory not found error

**Comment by wy580477** [comment]
>  ~$ curl -H "Content-Type: application/json" -X POST -d '{"re-1.2":2,"one":1}' http://localhost:61802/rc/noop Unauthorized

add "-u ${GLOBAL_USER}:${GLOBAL_PASSWORD}"

> and i was use copy command then show directory not found error

It's what it shows, rclone can't find the directory. Either you specify a non-existing dir or dir name has special characters which cause trouble for rclone.

**Comment by Th4Park** [comment]
hm it is solved but 

curl -s -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"srcFs":"re-1.2:/path_1","dstFs":"one:/path_2","_async":"true"}' 'localhost:61802/sync/copy'
{
        "jobid": 553
}

![image](https://user-images.githubusercontent.com/76167203/170417154-4fc0c302-1cb9-456a-a9a6-22805ae1ad8f.png)
