### ISSUE TITLE
Pyload [for xdcc]

### ISSUE THREAD

**Issue by z8512** [wy580477/Heroku-AIO-APP-EX#3]
Pyload is a powerful downloader which supports literally everything https://github.com/pyload/pyload/tree/main/src/pyload/plugins/downloaders
For rclone upload --> add a script in  `~/.pyload/scripts/download_finished`

**Comment by wy580477** [comment]
I tried it a while ago, feel a liitle buggy.

I will give it another try later.

**Comment by wy580477** [comment]
> True its buggy. But its only web-ui downloader which supports xdcc.

Done.

If you are upgrading from old deployment, add following to script.conf file:

```
# pyLoad auto-upload mode after download finished. move | copy | disable
pyload-download-finished-upload-mode=disable

# pyLoad auto-upload mode after package extracted. move | copy | disable
pyload-package-extracted-upload-mode=disable
```

**Comment by z8512** [comment]
@wy580477 Can you please give your https://simplex.chat address ? I want to talk with you❤
