### ISSUE TITLE
why there limit?

### ISSUE THREAD

**Issue by Strangelets** [wy580477/Heroku-AIO-APP-EX#5]
why there 5MB limit? what if i remove the limit lead to a ban?

**Comment by wy580477** [comment]
Frankly, I don‘t know.  I put a limit there to prevent unnecessary abuse of service. 

If you need more speed, feel to free to increase the limit at own risk. (I'm not saving that you dyno will be safe if you sticks with  the limit. This is a cat-and-mouse game.)

For now, heroku bans dyno based on git repo, image layer, keyword in deployment log & process name.

**Comment by wy580477** [comment]
I
