### ISSUE TITLE
rclone rc copy command is not working properly, upload is not working in, it downloads the same file again and again.

### ISSUE THREAD

**Issue by Th4Park** [wy580477/Heroku-AIO-APP-EX#6]
https://user-images.githubusercontent.com/76167203/170855485-677f2ef4-081b-499d-be64-25e2b9168361.mp4

i used this command = curl -s -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"srcFs":"M-720:/Anime","dstFs":"photos:album/m-720","_async":"true"}' 'localhost:61802/sync/copy'

copying google drive to google photos

**Comment by wy580477** [comment]
Well, I did a little test on onedrive. Copy command works fine.

I'm not a gd user. So I can't help you for this issue. I suggest you seek help from rclone community
